### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by Brutuss** [ping13/heospy#14]
Hi,

Great plugin! But I can't get something to work. I would like to use this command: 

`heos://browse/play_input?pid=xxxx&input=inputs/hdmi_in_1`
With Putty this command works. 

The command I need to use with this Python script I think is:
`heos_player browse/play_input -p input=inputs/hdmi_in_1`

This results in a Missing Command arguments error. 
Am I doing something wrong?

Greetings.

**Comment by Brutuss** [comment]
I think I can see were it is going wrong..

When you give the Original command in telnet, this works: 
`heos://browse/play_input?pid=xxxx&input=inputs/hdmi_in_1`

Entering the translated command with heospy: 
`heos_player browse/play_input -p input=inputs/hdmi_in_1`

The **pid** translates to **gid** and that is not working. 
`{
  "heos_message_parsed": {
    "eid": "3",
    "text": "Missing Command arguments",
    "gid": "-1070650677",
    "input": "inputs/hdmi_in_1"
  },
  "heos": {
    "message": "eid=3&text=Missing Command arguments&gid=-1070650677&input=inputs/hdmi_in_1",
    "command": "browse/play_input",
    "result": "fail"
  }
}`

**Comment by princebose08** [comment]
You would also need to pass gid as another argument.
This should work : `heos_player browse/play_input -p pid=xxxxxx -p input="inputs/hdmi_in_1"`

**Comment by Brutuss** [comment]
Have It working indeed with:

`heos_player browse/play_input -p input=inputs/hdmi_arc_1 -p pid=-1070650677 `

**Comment by ping13** [comment]
Thank your patience and sorry for not getting back to you earlier. You figured it out correctly, the default `gid` should most be passed on for any `browse` commands.  
This was a non-breaking bug and should be fixed with the latest commit and in `v0.2.5`.
