### ISSUE TITLE
Missing default pid for some browse commands

### ISSUE THREAD

**Issue by audetto** [ping13/heospy#19]
Try this

`heos_player browser/play_stream -p url=http://direct.franceinfo.fr/live/franceinfo-midfi.mp3`

it will fail because `pid` is missing.
The logic in https://github.com/ping13/heospy/blob/f1ddecaec264c8d0a0ef30d397c2db93dd96ae88/heospy/__init__.py#L303-L311 does not handle correctly `browse` commands.

I had already opened an issue a while ago https://github.com/ping13/heospy/issues/16 but it was not really fixed.

If it is too complicated to know which commands need a `pid` or a `gid`, why dont you add 2 flags to add default pid / gid. The user will know which commands need it.

**Comment by ping13** [comment]
Yes, default seems to be tricky. I've added the default `pid` to all commands starting with `browse/play_*`. I believe the default pid is not needed for any other `browse/` command.

**Comment by audetto** [comment]
Will this be merged? It works for me.
