### ISSUE TITLE
Work with more than one player.

### ISSUE THREAD

**Issue by ping13** [ping13/heospy#2]
The class `HeosPlayer` currently works with one HEOS player (as I only have one HEOS speaker). One should extend this to support multiple players, preferably with a default player for issuing commands.

The cache in the `config.json` file should contain the players, groups and sources.

**Comment by ping13** [comment]
It actually works with more than one player: the player in the config.json file is just the leader of a group. But this issue needs more thoughts and refactoring.

**Comment by ArjanPeeters** [comment]
It should also get the gid (group id). next to the already extracted pid. Then, things like group volume could work. Sadly, altho i can follow your script. I'm not good enough in python to actually dream this stuff up.

**Comment by ping13** [comment]
@ArjanPeeters You can get the group ids with 
```
python heos_player.py groups/get_groups
{
  "heos": {
    "command": "groups/get_groups",
    "result": "success",
    "message": "pid=-1352658342"
  },
  "payload": [
    {
      "name": "Living Room + Kitchen",
      "gid": -1352658342,
      "players": [
        {
          "name": "Wohnzimmer",
          "pid": -1352658342,
          "role": "leader"
        },
        {
          "name": "K\u00fcche",
          "pid": 941891005,
          "role": "member"
        }
      ]
    }
  ]
}

```

The main idea of storing the one player id in the config file was that I don't have to specify the player id as an argument as I issue commands like `player/toggle_mute`. So
```
python heos_player.py player/toggle_mute -p pid=-1352658342
```
is the same as
```
python heos_player.py player/toggle_mute
```
if the pid in the config file is stored as`-1352658342`.

However, it seems to me, that the group id is always identical to its lead player id. So with the latest commit 1aaaefb16b5a5df315b06f5ee28e130d004f5003, you can also do 
```
python heos_player.py group/toggle_mute 
```
instead of
```
python heos_player.py group/toggle_mute -p gid=-1352658342
```
(obviously, use your actual player/group id instead of `-1352658342`).

Note that my use case is that I only have one group of speakers, that's why this is convenient for me.

**Comment by ping13** [comment]
I close this as the script no works sufficiently with multiple players and multiple groups: you either can use the default pid in the config file for convenience or you can explicitly set the id, e.g. with
```
python heos_player.py player/toggle_mute -p pid=941891005
```
for a player different from the main player in the config file.

**Comment by ArjanPeeters** [comment]
ping13, Thank you very much! I'm only beginning to learn python and this helps me very much. Much appreciated!
