### ISSUE TITLE
Strange behaviour of config file location

### ISSUE THREAD

**Issue by audetto** [ping13/heospy#20]
This change https://github.com/ping13/heospy/commit/bafcfa2b6a4de0c0cbc36699f7e34465e2e65f73 has the unwanted (?) side effect of disabling `$HOME/.heospy/` as a valid location of `config.json`.

I dont think this line makes sense: https://github.com/ping13/heospy/blob/f1ddecaec264c8d0a0ef30d397c2db93dd96ae88/heospy/__init__.py#L32

It searches twice in the same location, and never in `.heospy`.

**Comment by ping13** [comment]
Thanks for reporting, this change was stupid - sorry about this.
