### ISSUE TITLE
heospy should be a pypi published package

### ISSUE THREAD

**Issue by ssbarnea** [ping13/heospy#8]
heospy should be published on PYPI and installable from there.

I already made the required changes to do this and published the current version but I was not able to add @ping13 to owners. Please post you PYPI username (or register with the same github user) so I can add you.

**Comment by ping13** [comment]
Thank you for the pull request and your initiative.
I've registered on PYPI as `ping13`. Let me know if you need something else.

**Comment by ping13** [comment]
Hi @ssbarnea , could you add me to the owners of https://pypi.org/project/heospy/? I'd like to try to update the package. Thanks

**Comment by ssbarnea** [comment]
@ping13 Done! Sorry for the delay in reading email. Release on pypi can fully be automated via travis when you push a new tag.

**Comment by ping13** [comment]
@ssbarnea Great, thanks so much. I was new to travis, but with some fiddling, I managed to deploy it.
